---
title: "STAT_5014_2019_hc704_HW1"
author: "chenhan"
date: "8/30/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem 2

Now that we have the R environment setup and have a basic understanding of R, let's add Markdown (choose File, New File, R Markdown, pdf).  

Let's go ahead and save the file as is.  Save the file to the directory containing the *README.md* file you created and committed to your git repo in Homework 0.  The filename should be: HW1_pid, i.e. for me it would be HW1_rsettlag.

You will use this new R Markdown file for the remainder of this homework.


### Part A
In this new Rmarkdown file, please type a paragraph about what you are hoping to get out of this class.  Include at least 3 specific desired learning objectives in list format. 

- Using tools inlcuding RStudio, GitHub, Overleaf and more to create reproduciable and 
- 


### Part B
To this, add 3 density functions (Appendix Cassella & Berger) in centered format with equation number, i.e. format this as you would find in a journal.

- The pdf of normal distribution
$$ f(x|\mu, \sigma^2) = \frac{1}{\sqrt{2\pi\sigma^2}} e^{-\frac{(x-\mu)^2}{\sigma^2}} $$

-

# Problem 3

A quote from Donoho (1995): "an article about computational results is advertising, not scholarship. The actual scholarship is the full software environment, code and data, that produced the result."  To the document created in Problem 4, add a summary of the steps in performing Reproducible Research in numbered list format as detailed in:  
<http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003285>.  
\newline
Next to each item, comment on any challenges you see in performing the step.  If you are interested in learning more, a good summary of why this is important can be found in  
- <https://www.informs.org/ORMS-Today/Public-Articles/October-Volume-38-Number-5/Reproducible-Operations-Research>  
- <https://doi.org/10.1093/biostatistics/kxq028>  
- <http://statweb.stanford.edu/~wavelab/Wavelab_850/wavelab.pdf>

# Problem 4

Please create and include a basic scatter plot and histogram of an internal R dataset.  To get a list of the datasets available use `library(help="datasets")`.


**This document containing solutions to Problems 2-4 should be typed in RMarkdown, using proper English, and knitted to create a pdf document.  Do NOT print, we will use git to submit this assignment as detailed below.**

# Problem 5
Please knit this document to PDF (name should be `HW2_pid`) and push to GitHub:

In the R Terminal, type:  
\begin{enumerate}
    \item git pull  
    \item git add HW1\_pid.[pR]*  (NOTE: this should add two files)  
    \item git commit -m "final HW2 submission"   
    \item git push
\end{enumerate}

A more detailed description is on the course website under *Submitting Homework*.

## Reminder on where to find Git help:  
Read through the Git help Chapters 1 and 2. <https://git-scm.com/book/en/v2>